// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceManageGroup.Data;

#nullable disable

namespace ResourceManageGroup.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("EmployeeSequence", "dbo");

            modelBuilder.HasSequence<int>("ManagerSequence", "dbo");

            modelBuilder.HasSequence<int>("RecruiterSequence", "dbo");

            modelBuilder.Entity("ResourceManageGroup.Models.Employee", b =>
                {
                    b.Property<string>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("CONCAT('23EM', RIGHT('00' + CAST(NEXT VALUE FOR EmployeeSequence AS VARCHAR(2)), 2))");

                    b.Property<int>("employeeAge")
                        .HasColumnType("int");

                    b.Property<string>("employeeConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("employeeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("employeeName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("employeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeePassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeTechnology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeTrainerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeTrainingEndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeTrainingStartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeVacationEndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeVacationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeVacationStartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeVacationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeWorkingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employeeId");

                    b.ToTable("EmployeeDetails");
                });

            modelBuilder.Entity("ResourceManageGroup.Models.Manager", b =>
                {
                    b.Property<string>("managerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("CONCAT('23PM', RIGHT('00' + CAST(NEXT VALUE FOR ManagerSequence AS VARCHAR(2)), 2))");

                    b.Property<string>("managerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("managerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("managerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("managerPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("managerId");

                    b.ToTable("ManagerDetails");
                });

            modelBuilder.Entity("ResourceManageGroup.Models.Project", b =>
                {
                    b.Property<int>("projectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("projectId"));

                    b.Property<string>("projectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectEndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectLead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectStartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("projectId");

                    b.ToTable("ProjectDetails");
                });

            modelBuilder.Entity("ResourceManageGroup.Models.Recruiter", b =>
                {
                    b.Property<string>("recruiterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("CONCAT('23HR', RIGHT('00' + CAST(NEXT VALUE FOR RecruiterSequence AS VARCHAR(2)), 2))");

                    b.Property<string>("recruiterEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("recruiterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("recruiterNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("recruiterPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("recruiterId");

                    b.ToTable("RecruiterDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
